import Image from 'next/image'
import Link from 'next/link'
import { ArrowLeft, Info, LockKeyhole } from 'lucide-react'
import { Brand } from '@/components/site-header'
import { Alert, AlertTitle, AlertDescription } from '@/components/ui/alert'
import { Field, FieldGroup, FieldLabel } from '@/components/ui/field'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'

export function AuthEntry({ signup = false, next = '/account' }: { signup?: boolean; next?: string }) {
  const owner = next.startsWith('/owner')
  const switchUrl = `${signup ? '/login' : '/signup'}?next=${encodeURIComponent(next)}`
  return <main id="main" className="flex min-h-svh"><section className="flex w-full flex-col p-6 md:p-12 lg:w-1/2"><Brand /><div className="mx-auto flex w-full max-w-sm flex-1 flex-col justify-center gap-6 py-12"><Link href="/" className="text-link"><ArrowLeft className="size-4" />Back to ChaloPG</Link><div className="flex flex-col gap-3"><p className="eyebrow">{owner ? 'For property owners' : 'Make yourself at home'}</p><h1 className="text-4xl font-semibold tracking-tight">{signup ? 'Your next chapter.' : 'Welcome back.'}</h1><p className="text-sm leading-relaxed text-muted-foreground">{owner ? 'Your space deserves to be discovered. Start with an owner account.' : 'A place for your saved spaces, conversations, and visit requests.'}</p></div><Alert className="p-4"><Info /><AlertTitle>Accounts are awaiting setup</AlertTitle><AlertDescription>Secure authentication and the database have not been connected. Registration and login are disabled; no information will be submitted.</AlertDescription></Alert><fieldset disabled aria-label={signup ? 'Registration unavailable' : 'Login unavailable'}><FieldGroup>{signup && <Field><FieldLabel htmlFor="full-name">Full name</FieldLabel><Input id="full-name" autoComplete="name" placeholder="Your full name" className="h-11" /></Field>}<Field><FieldLabel htmlFor="email">Email address</FieldLabel><Input id="email" type="email" autoComplete="email" placeholder="you@example.com" className="h-11" /></Field><Field><FieldLabel htmlFor="password">Password</FieldLabel><Input id="password" type="password" autoComplete={signup ? 'new-password' : 'current-password'} placeholder="Enter your password" className="h-11" /></Field><Button disabled className="h-11"><LockKeyhole data-icon="inline-start" />{signup ? 'Registration unavailable' : 'Login unavailable'}</Button></FieldGroup></fieldset><p className="text-center text-sm text-muted-foreground">{signup ? 'Already have an account?' : 'New to ChaloPG?'} <Link className="font-semibold text-primary" href={switchUrl}>{signup ? 'Log in' : 'Create an account'}</Link></p><Link href="/setup" className="text-center text-sm text-primary underline underline-offset-4">View setup requirements</Link></div><p className="text-sm text-muted-foreground">ChaloPG · Find a place. Feel at home.</p></section><aside className="relative hidden w-1/2 lg:block"><Image src="/images/chalopg-home.png" alt="Comfortable shared apartment with warm natural light" fill sizes="50vw" priority className="object-cover" /><div className="absolute right-10 bottom-10 left-10 rounded-2xl bg-background/95 p-7"><h2 className="text-3xl font-semibold tracking-tight">A new city.<br /><span className="text-primary">A familiar feeling.</span></h2><p className="pt-3 text-sm leading-relaxed text-muted-foreground">Find a little space to grow, unwind, and make your own.</p></div></aside></main>
}
